---
name: Build
"on":
  push:
    branches:
      - '*'
    tags:
      - '!**'

jobs:

  test:
    runs-on: ubuntu-20.04
    container: mfontani/gobuzz
    steps:
      - uses: actions/checkout@v3
      - run: go mod download
      - run: go vet

  build:
    needs: [test]
    runs-on: ubuntu-20.04
    container: mfontani/gobuzz
    steps:
      - uses: actions/checkout@v3
      - run: go mod download
      - run: ./.dev/build-static.sh
      - run: ./xlsx2tsv -help
